### ISSUE TITLE
[Feature Request] Permissions based on state

### ISSUE THREAD

**Issue by andevellicus** [meowosaurus/aa-simplewiki#1]
Group-based permissions are great, is there a way to add state-based permissions for menus/sections?

**Comment by meowosaurus** [comment]
Hey, right now it's not possible, but I should be able to implement it within a week.

**Comment by meowosaurus** [comment]
Hey, right now it's not possible, but I should be able to implement it within a week.

**Comment by skuldomg** [comment]
> Hey, right now it's not possible, but I should be able to implement it within a week.

Hi there! This would be a great feature. Are you still maintaining this project? There's only one other AA based Wiki I've seen and it would be sad to lose this one :)

**Comment by meowosaurus** [comment]
Hey, I'm still working on it, currently working on the last finished for the v1.1 update.
