### ISSUE TITLE
Error when creating section without index

### ISSUE THREAD

**Issue by swashman** [meowosaurus/aa-simplewiki#12]
### Bug Description
Editor_section_error_unknown when adding section without entering an index.

### Steps to Reproduce

Create section and don't add a number for index

### Expected behavior
Item says optional so should default to 0

### Screenshots
![image-4.png](https://github.com/user-attachments/assets/366ae412-95df-4fa4-b5b2-c6c1a04ee6a0)

### Please complete the following information:

- App Version:2.0.3
- Alliance Auth Version:latest
- Browser and Version:

**Comment by meowosaurus** [comment]
Fixed with upcoming v2.1
