### ISSUE TITLE
First page defaults to oldest created instead of lowest index

### ISSUE THREAD

**Issue by skuldomg** [meowosaurus/aa-simplewiki#2]
### Bug Description

The /wiki/ link seems to default to the oldest created menu and its sections.

### Steps to Reproduce

1. Create a menu with the index 0.
2. Create a section with that menu as its parent.
3. Create a second menu with the index 1.
4. Create a section with that menu as its parent.
5. Now switch the indexes of the two created menus.
6. Go to Alliance Auth /wiki/
7. It shows menu 1 and its sections (the one we created first) instead of menu 0.

### Expected behavior

The /wiki/ link should always show the menu and its sections with the lowest index.

### Screenshots

![image](https://github.com/meowosaurus/aa-simplewiki/assets/6090045/d3f51532-8cf3-47ef-b73a-72312dc9141e)
(View after clicking the wiki link)

![image](https://github.com/meowosaurus/aa-simplewiki/assets/6090045/8430cac6-431f-4e15-a9e0-9976aedd7e57)
(Menu config)

### Please complete the following information:

- App Version: Latest
- Alliance Auth Version: 3.7.0
- Browser and Version: Latest Chrome

**Comment by meowosaurus** [comment]
Hey, I'm currently working on a fix for it. Will come with v1.1
