### ISSUE TITLE
Can't Edit Section Index

### ISSUE THREAD

**Issue by swashman** [meowosaurus/aa-simplewiki#4]
### Bug Description

When creating or editing a section, the index always sets to 0 regardless of what you have set.

### Steps to Reproduce

1) Create or edit a section
2) set index to a value other than 0
3) save section
4) section shows as index 0 on section administration page. Also shows as 0 in admin.

Value edits properly in admin

### Expected behavior

Set index to entered value

### Please complete the following information:

- App Version: 1.1.1
- Alliance Auth Version:3.8.0
- Browser and Version: chrome

**Comment by swashman** [comment]
Further update, sections don't seem to be respecting the set index and are ordering based on creation order

**Comment by meowosaurus** [comment]
Both fixed with update 1.1.2
