### ISSUE TITLE
[Feature Request]  table of contents

### ISSUE THREAD

**Issue by swashman** [meowosaurus/aa-simplewiki#5]
### Context
Pages with multiple and/or long sections.

### Describe the feature you have in mind

A table of contents of some form, to be able to jump down a page to the section you would like to view.
Aside from just being lazy compared to scrolling, this would also allow a quick view to see if a page contains something you might be looking for.

**Comment by meowosaurus** [comment]
Interesting idea, will add it to my to-do list.

**Comment by meowosaurus** [comment]
Added with v1.1.3
